[package]
name = "jca"
version = "0.1.0"
authors = ["Aaron Hill <aaron_hill2@carleton.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
